# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu_Home = QtWidgets.QMenu(self.menuBar)
        self.menu_Home.setObjectName("menu_Home")
        self.menuExtract = QtWidgets.QMenu(self.menuBar)
        self.menuExtract.setObjectName("menuExtract")
        MainWindow.setMenuBar(self.menuBar)
        self.actionWelcome_Page = QtWidgets.QAction(MainWindow)
        self.actionWelcome_Page.setObjectName("actionWelcome_Page")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionCredits = QtWidgets.QAction(MainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.actionExtract_E = QtWidgets.QAction(MainWindow)
        self.actionExtract_E.setObjectName("actionExtract_E")
        self.actionExtract = QtWidgets.QAction(MainWindow)
        self.actionExtract.setObjectName("actionExtract")
        self.menu_Home.addAction(self.actionWelcome_Page)
        self.menu_Home.addAction(self.actionDocumentation)
        self.menu_Home.addAction(self.actionCredits)
        self.menuExtract.addAction(self.actionExtract_E)
        self.menuExtract.addAction(self.actionExtract)
        self.menuBar.addAction(self.menu_Home.menuAction())
        self.menuBar.addAction(self.menuExtract.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ricette-Italiana Scraper Utility"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menu_Home.setTitle(_translate("MainWindow", "&Home"))
        self.menuExtract.setTitle(_translate("MainWindow", "Tools"))
        self.actionWelcome_Page.setText(_translate("MainWindow", "Welcome Page"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionCredits.setText(_translate("MainWindow", "Credits"))
        self.actionExtract_E.setText(_translate("MainWindow", "Scrape..."))
        self.actionExtract.setText(_translate("MainWindow", "Extract..."))
